version: '3'


services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-store
    container_name: mg-nest-store
    volumes:
      - ./mongo:/data/bd
  db2:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: pg-nest-store
    volumes:
      - ./postgres:/var/lib/postgresql/data